src/objects/Property__c.object
<CustomObject>
    <fields>
        <fullName>Baths__c</fullName>
        <label>Baths</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Beds__c</fullName>
        <label>Beds</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Properties</relationshipLabel>
        <relationshipName>Properties</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pre-Market</fullName>
                </value>
                <value>
                    <fullName>Listed</fullName>
                </value>
                <value>
                    <fullName>Under Contract</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Thumbnail__c</fullName>
        <label>Thumbnail</label>
        <type>Url</type>
    </fields>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DB_PropertySelector.cls
public virtual class DB_PropertySelector extends fflib_SObjectSelector {
	private static final Decimal DEFAULT_PRICE = 1;
	private static final Decimal DEFAULT_PRICE_RANGE = 100000;

    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField>{
                Property__c.Baths__c,
                Property__c.Beds__c,
                Property__c.Broker__c,
                Property__c.Id,
                Property__c.Name,
                Property__c.Price__c,
                Property__c.Status__c,
                Property__c.Thumbnail__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Property__c.sObjectType;
    }

    public List<Property__c> selectByNumberOfBeds(Decimal numberOfBeds, Id excludedProperty) {
		return (List<Property__c>) Database.query(
			newQueryFactory()
				.setCondition('beds__c = :numberOfBeds AND id != :excludedProperty')
				.toSOQL()
		);
    }

    public List<Property__c> selectByPriceRange(Decimal price, Decimal priceRange, Id excludedProperty) {
		Decimal searchPrice = (price != null) ? price : DEFAULT_PRICE;
    	Decimal searchRange = (priceRange != null) ? priceRange : DEFAULT_PRICE_RANGE;
    	Decimal minimum = searchPrice - searchRange;
    	Decimal maximum = searchPrice + searchRange;
    	return (List<Property__c>) Database.query(
			newQueryFactory()
				.setCondition('price__c > :minimum AND price__c < :maximum AND id != :excludedProperty')
				.toSOQL()
		);
    }

}